[server]
pre_game_wait = 5                       # time in seconds to wait before a game starts
tick_wait_time = 5                      # time in seconds for each tick to wat for commands
terminal_map = false                    # draw a map in the terminal
log_dir = "logs"                        # log file directory, don't change during runtime
scores_file = "scores.log"              # the file to store total score over multiple games

[game]
map_size = 16                           # the size of the map in fields
max_score = 25                          # game end if a team reaches or exceeds that score
max_ticks = 200                         # game ends after this number of ticks
capture_score = 5                       # number of points awarded for capturing a flag
kill_score = 1                          # number of points awarded for killing an actor
winning_bonus = 10                      # number of points awarded for winning a game
home_flag_required = false              # does the team flag need to be at home base to score?
map_style = 'arabia'                    # Styles: arabia, blood_bath, black_forest, random. (random is random style, not random map)
walls = 0.15                            # Target integer number of walls (+- symmetries), or floating percentage of walls
actors =    ["Runner", 
            "Runner", 
            "Attacker", 
            "Attacker"]                 # the actor types that are present in the game


[image]                                 # the image size used to render the status image on status web-page
size = 980

[[teams]]                               # the list of teams participating
name = "Team 1"
password = "1"

[[teams]]
name = "Team 2"
password = "2"

